### ISSUE TITLE
Generate JSON data

### ISSUE THREAD

**Issue by nt1m** [bgrins/xbl-analysis#3]
I'm making a twitter bot based on this repo, and it would be really useful if you could generate JSON data of:
- the removal timeline
- the statistics about LOC and number of bindings in JSON : https://github.com/bgrins/xbl-analysis/blob/gh-pages/graph/xbl-counts.js

**Comment by nt1m** [comment]
I worked around the lack of JSON: https://twitter.com/mozxbl

Source is here: https://github.com/nt1m/xbl-twitter-bot

@bgrins Would you mind adding a Github webhook to http://xbl-bot.herokuapp.com/tweet ?

**Comment by bgrins** [comment]
Webhook added

**Comment by bgrins** [comment]
I think it would make sense to generate JSON and then have the other scripts read that JSON rather than re-processing the same files. I don't think I'll have time to work on that soon, though.

However, creating a timeline JSON file in https://github.com/bgrins/xbl-analysis/blob/gh-pages/scripts/build-timeline.js seems like a relatively easy chunk of work that would help with the bot.

**Comment by bgrins** [comment]
I also realized that https://github.com/bgrins/xbl-analysis/blob/gh-pages/graph/xbl-counts.js is really big, so that can't be great for the bot. We could generate a *way* smaller file that includes just LOC and # of bindings per day (maybe add that the timeline JSON mentioned in the above comment)

**Comment by nt1m** [comment]
Yep, it would be nice to have a JSON file that just contains the main stats + the timeline :)
